{# Copyright (c) Pelagicore AB 2016 #}
{% import "qface/qtcpp.j2" as cpp %}
{{ cpp.autogenerated()}}
{% set major = module.majorVersion %}
{% set minor = module.minorVersion %}
#include "plugin.h"

#include <qqml.h>

{% for interface in module.interfaces %}
#include "{{interface|lower}}client.h"
{% endfor %}

Plugin::Plugin(QObject *parent)
    : QQmlExtensionPlugin(parent)
{
}

void Plugin::initializeEngine(QQmlEngine *engine, const char *uri)
{
    Q_UNUSED(engine)
    Q_UNUSED(uri)
}

void Plugin::registerTypes(const char *uri)
{
    // @uri {{module}}
{% for interface in module.interfaces %}
    qmlRegisterType<{{module|qt.ns}}{{interface}}Client>(uri, {{major}}, {{minor}}, "{{interface}}Client");
{% endfor %}

{% for struct in module.structs %}
    qRegisterMetaType<{{struct}}>();
    qmlRegisterUncreatableType<{{struct}}Factory>(uri, {{major}}, {{minor}}, "{{struct}}Factory", "Factory can not be created");
{% endfor %}

}
